### ISSUE TITLE
use predefined errors

### ISSUE THREAD

**Issue by bokunodev** [aidantwoods/go-paseto#11]
probably something insignificant and can be done by user. 
but, having errors that you can assert would be great.

**Comment by lafriks** [comment]
also would be nice to fix error messages to have first lowercase letter (as per go recommendations)

**Comment by aidantwoods** [comment]
Thanks for bringing this up! 👍 are you looking specifically for the rules the have assertable error messages? Or would it also be useful to export some of the errors from [errors.go](https://github.com/aidantwoods/go-paseto/blob/main/errors.go)?

**Comment by aidantwoods** [comment]
No need to wait for those PRs if you'd like to open one, they can always be rebased 🙂

I'll try to find some time to get this out soon

**Comment by lafriks** [comment]
My use case would probably to be able to easy recognize such cases:
* invalid token errors (format, encoding etc)
* validation errors (expired etc)
* other errors

**Comment by aidantwoods** [comment]
That makes complete sense. Once I've got something up, can I tag you both to take a look to make sure it's fitting your desired use cases? 🙂

**Comment by aidantwoods** [comment]
I've opened https://github.com/aidantwoods/go-paseto/pull/12 to address this 🙂 

I'd appreciate a review at your leisure to make sure that this is going to catch things you're interested in. I've intentionally left some things as generic errors (like failing to construct a key), since I'm not sure that use case really warrants a custom type (only one thing can really go wrong when calling into those functions).

**Comment by lafriks** [comment]
Looks good for my use case

**Comment by aidantwoods** [comment]
Now available on latest release [`v1.2.0`](https://github.com/aidantwoods/go-paseto/releases/tag/v1.2.0)! 😄
